#!/bin/bash

set -ex
HERE=$PWD
. ${HERE}/hooks/common.sh

#juju-log "installing torch"
#curl -s https://raw.githubusercontent.com/mehdidc/torch-install/master/install-all | bash

juju-log "Installing itorch notebook"
luarocks install itorch
ipython profile create torch
echo "hi"
echo 'c.KernelManager.kernel_cmd = ["/usr/local/bin/itorch_launcher","{connection_file}"]' >> $IPYTHON/profile_torch/ipython_config.py
echo "c.Session.key = b''" >> $IPYTHON/profile_torch/ipython_config.py
echo "c.Session.keyfile = b''" >> $IPYTHON/profile_torch/ipython_config.py

juju-log "Installing auto start"
sed -i s/PROFILE/${PROFILE}/g ${HERE}/data/${DEFAULT}
sed -i "s|CONFIG_FOLDER|${IPYTHON}|g" ${HERE}/data/${DEFAULT}
sed -i "s|HOMEPATH|${HOMEPATH}|g" ${HERE}/data/${DEFAULT}

ln -sf ${HERE}/data/${DEFAULT} /${DEFAULT}
ln -sf ${HERE}/data/${INIT} /${INIT}
chmod 0755 /${INIT}
chown root:root /${INIT}
update-rc.d ${APPNAME} defaults

juju-log "Installation done. Moving to configuration"

${HERE}/hooks/stop || echo "Not started. Moving forward"

# juju-log "Setting password for Web GUI"
NEW_PASSWORD=`config-get password`
if [ "$NEW_PASSWORD" = "" ]; then
     NEW_PASSWORD = "secret"
     juju-log "Password cannot be empty. Using 'secret' as password"
    config-set password ${NEW_PASSWORD}
fi
PASSWORD=`python -c "import IPython;print IPython.lib.passwd(\"${NEW_PASSWORD}\")"`

juju-log "Creating new configuration"
[ -d ${CONFIG_FOLDER} ] && rm -rf ${CONFIG_FOLDER}

#sudo -u ${USER} ipython profile create ${PROFILE}
cp -f ${HERE}/data/etc/${APPNAME}/${CONFIG_FILE}.template ${CONFIG_FOLDER}/${CONFIG_FILE}

sed -i "s|CONFIG_FOLDER|${CONFIG_FOLDER}|g" ${CONFIG_FOLDER}/${CONFIG_FILE}
sed -i s/^c\.NotebookApp\.password.*/c\.NotebookApp\.password\ \=\ u\'"${PASSWORD}"\'/g ${CONFIG_FOLDER}/${CONFIG_FILE}

juju-log "Creating SSL autosigned certificate"
cd ${CONFIG_FOLDER}
openssl req -new -newkey rsa:1024 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=jujunotebook" -keyout jujunotebook.pem -out jujunotebook.pem
cd -

juju-log "Installation done. Moving to configuration"
exit 0
